"""followers

Revision ID: 7888ed96bd9c
Revises: c3e149244f11
Create Date: 2018-07-29 15:08:44.530699

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7888ed96bd9c'
down_revision = 'c3e149244f11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
